env:
   global:
     - CONAN_REFERENCE: "logr/0.5.2"
     - CONAN_USERNAME: "ngrodzitski"
     - CONAN_LOGIN_USERNAME: "ngrodzitski"
     - CONAN_CHANNEL: "testing"
     - CONAN_BUILD_POLICY=missing
     - CONAN_RUN_TESTS=True

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9

      - <<: *linux
        env: CONAN_GCC_VERSIONS=10 CONAN_DOCKER_IMAGE=conanio/gcc10

      # Requires Boost build, which eats travis credits....
      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=11 CONAN_DOCKER_IMAGE=conanio/gcc11


      - <<: *linux
        env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=10 CONAN_DOCKER_IMAGE=conanio/clang10

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=11 CONAN_DOCKER_IMAGE=conanio/clang11

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

notifications:
  email:
    recipients:
      - utromvecherom@gmail.com
