build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_REFERENCE: "logr/0.4.0"
    CONAN_USERNAME: "ngrodzitski"
    CONAN_LOGIN_USERNAME: "ngrodzitski"
    CONAN_CHANNEL: "testing"
    CONAN_BUILD_POLICY: "missing"
    CONAN_RUN_TESTS: "True"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16


install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
